name: Build Native AOT App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest  # or 'ubuntu-latest' for Linux builds

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - name: Publish AOT
      run: dotnet publish -c Release
